services:
  web-app:
    image: ghcr.io/${REPO_NAME_LOWER}/web-app:${IMAGE_TAG}
    restart: always
    ports:
      - "80:3000"
    environment:
      - DATABASE_URL=mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@mysql:3306/${MYSQL_DATABASE}
      - RUST_ENGINE_URL=http://rust-engine:8000
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    depends_on:
      - mysql
      - rust-engine

  rust-engine:
    image: ghcr.io/${REPO_NAME_LOWER}/rust-engine:${IMAGE_TAG}
    restart: always
    environment:
      - DATABASE_URL=mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@mysql:3306/${MYSQL_DATABASE}
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - mysql-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "127.0.0.1:8080:80"
    environment:
      - PMA_HOST=mysql
    depends_on:
      - mysql

volumes:
  mysql-data:
